// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Nuestra Misión"
          title="Más que una web bonita."
          description="En Digital Rocket diseñamos páginas web para dentistas, clínicas, inmobiliarias, despachos y negocios locales que quieren que su web trabaje: atraer llamadas, reservas y contactos reales cada semana."
          imageSrc="https://storage.googleapis.com/webild/users/user_3G7lP4hAI7lZ4o4pKdNJOJn1cYO/uploaded-1783349794313-95heaxlx.png"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
