// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Nuestra Misión"
          title="Más que una web bonita."
          description="En Digital Rocket diseñamos páginas web para dentistas, clínicas, inmobiliarias, despachos y negocios locales que quieren que su web trabaje: atraer llamadas, reservas y contactos reales cada semana."
          imageSrc="https://images.pexels.com/photos/6627924/pexels-photo-6627924.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=6627924"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
