// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="Nuestra Misión"
          title="Más que Diseño Web"
          description="En Digital Rocket, combinamos excelencia técnica con diseño estratégico para asegurar que tu web atraiga pacientes, clientes e inversores para tu clínica, constructora o inmobiliaria."
          imageSrc="http://img.b2bpic.net/free-photo/group-young-businesswomen-sitting-modern-office-talking-each-other_23-2147955160.jpg"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
