// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="¿Listo para despegar?"
          text="Construyamos algo extraordinario para tu negocio."
          primaryButton={{
            text: "Contáctanos",
            href: "mailto:hello@digitalrocket.com",
          }}
          secondaryButton={{
            text: "Agendar Llamada",
            href: "#",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
