// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBentoGrid
          tag="Por qué elegirnos"
          title="Diseñado para el Éxito de tu Negocio"
          description="Soluciones digitales optimizadas para captar más clientes, pacientes o inversores."
          features={[
            {
              title: "Portales para Pacientes",
              description: "Sistemas seguros y fáciles de usar para clínicas y consultorios.",
              imageSrc: "https://images.pexels.com/photos/12238860/pexels-photo-12238860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=12238860",
            },
            {
              title: "Catálogos Inmobiliarios",
              description: "Muestra tus propiedades con galerías de alta calidad y filtros avanzados.",
              imageSrc: "https://images.pexels.com/photos/13270594/pexels-photo-13270594.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=13270594",
            },
            {
              title: "Portafolios de Proyectos",
              description: "Destaca las obras de tu constructora con un diseño impactante.",
              imageSrc: "https://images.pexels.com/photos/35300835/pexels-photo-35300835.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=35300835",
            },
            {
              title: "Optimización SEO Local",
              description: "Aparece primero cuando busquen tus servicios en tu ciudad.",
              imageSrc: "http://img.b2bpic.net/free-photo/ui-ux-representations-with-smartphone_23-2150201873.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
