// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBentoGrid
          tag="Por qué elegirnos"
          title="Diseñado para el Éxito de tu Negocio"
          description="Soluciones digitales optimizadas para captar más clientes, pacientes o inversores."
          features={[
            {
              title: "Portales para Pacientes",
              description: "Sistemas seguros y fáciles de usar para clínicas y consultorios.",
              imageSrc: "http://img.b2bpic.net/free-photo/menu-circle-button-front-side-white-background_187299-40323.jpg",
            },
            {
              title: "Catálogos Inmobiliarios",
              description: "Muestra tus propiedades con galerías de alta calidad y filtros avanzados.",
              imageSrc: "http://img.b2bpic.net/free-photo/battery-low-front-side-with-white-background_187299-39726.jpg",
            },
            {
              title: "Portafolios de Proyectos",
              description: "Destaca las obras de tu constructora con un diseño impactante.",
              imageSrc: "http://img.b2bpic.net/free-photo/abstract-different-colored-draw-paper_23-2147747577.jpg",
            },
            {
              title: "Optimización SEO Local",
              description: "Aparece primero cuando busquen tus servicios en tu ciudad.",
              imageSrc: "http://img.b2bpic.net/free-photo/ui-ux-representations-with-smartphone_23-2150201873.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
