// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitVerticalMarquee from '@/components/sections/hero/HeroSplitVerticalMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitVerticalMarquee
          tag="Diseño Web para Pequeñas Empresas"
          title="Crea tu Presencia Digital Profesional"
          description="Diseñamos y desarrollamos sitios web a medida para ayudar a tu pequeña empresa a destacar en internet y atraer más clientes."
          primaryButton={{
            text: "Iniciar Proyecto",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Ver Trabajos",
            href: "#product",
          }}
          leftItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/view-3d-space-rocket-model_23-2151113325.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/background-with-printed-circuit-board-concept-modern-technologies_169016-61853.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/horizontal-detail-no-people-macro-close-up_1122-2363.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/abstract-dynamic-light-streaks-dark-background_84443-82408.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/low-poly-background-with-connecting-lines-dots_1048-6496.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/gradient-technology-background_23-2151895852.jpg",
            },
          ]}
          rightItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/user-people-network-circuit-board-link-connection-technology_1379-886.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/specialist-using-laptop-troubleshooting-data-center-mainframes-with-high-computing-power-enabling-hyperscale-server-hub-support-demanding-applications-such-as-machine-learning-workloads_482257-67945.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-programming-code-language_53876-15056.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-abstract-technology-with-flowing-cyber-particles_1048-15470.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/circuit-board-close-up-with-different-connections_23-2149174310.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-glass-geometric-shapes_23-2150979642.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
