// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Impacto"
          title="Impacto y éxito basado en datos"
          description="No adivinamos, optimizamos con métricas precisas."
          metrics={[
            {
              value: "150+",
              description: "Proyectos entregados",
            },
            {
              value: "98%",
              description: "Satisfacción del cliente",
            },
            {
              value: "5x",
              description: "Más velocidad media",
            },
            {
              value: "200%",
              description: "Crecimiento promedio en conversiones",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
