// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Impact"
          title="Data-Driven Success"
          description="We don't guess, we optimize with precision metrics."
          metrics={[
            {
              value: "150+",
              description: "Projects Delivered",
            },
            {
              value: "98%",
              description: "Client Satisfaction",
            },
            {
              value: "5x",
              description: "Average Speed Increase",
            },
            {
              value: "200%",
              description: "Avg Conversion Growth",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
