// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "product" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductSection(): React.JSX.Element {
  return (
    <div id="product" data-section="product">
        <SectionErrorBoundary name="product">
              <FeaturesImageBento
          tag="Nuestro Portafolio"
          title="Excelencia en Cada Sector"
          description="Explora nuestros casos de éxito en clínicas, inmobiliarias y constructoras."
          items={[
            {
              title: "Plataforma Médica",
              description: "Full stack architecture.",
              imageSrc: "http://img.b2bpic.net/free-photo/office-worker-analyzing-business-charts-laptop-using-paperwork-research-information-make-data-report-working-from-home-startup-analysis-with-web-graphs-browsing-internet_482257-50961.jpg",
            },
            {
              title: "E-commerce Store",
              description: "Conversion-focused shops.",
              imageSrc: "http://img.b2bpic.net/free-photo/stylish-clothing-boutique-interior_23-2151961902.jpg",
            },
            {
              title: "Corporate Site",
              description: "Professional brand presence.",
              imageSrc: "http://img.b2bpic.net/free-photo/office-worker-analyzing-online-statistics-copy-space-mockup_482257-123748.jpg",
            },
            {
              title: "Mobile Web App",
              description: "Highly interactive UI.",
              imageSrc: "http://img.b2bpic.net/free-photo/representation-user-experience-interface-design_23-2150169839.jpg",
            },
            {
              title: "Portfolio Site",
              description: "Creative visual showcases.",
              imageSrc: "http://img.b2bpic.net/free-photo/view-nutritional-counter-app_23-2149880610.jpg",
            },
            {
              title: "Dashboard UI",
              description: "Data-heavy application.",
              imageSrc: "http://img.b2bpic.net/free-photo/financial-application-ui-pc-screen-showing-company-revenue_482257-119232.jpg",
            },
            {
              title: "Marketing Site",
              description: "High engagement funnel.",
              imageSrc: "http://img.b2bpic.net/free-photo/female-web-designer-with-papers-notes-office_23-2149749877.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
