// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "product" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductSection(): React.JSX.Element {
  return (
    <div id="product" data-section="product">
        <SectionErrorBoundary name="product">
              <FeaturesImageBento
          tag="Nuestro Portafolio"
          title="Excelencia en Cada Sector"
          description="Explora nuestros casos de éxito en clínicas, inmobiliarias y constructoras."
          items={[
            {
              title: "SB Capital",
              description: "Sitio web corporativo para empresa de inversión. Visita: sbcapital.es",
              imageSrc: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
            },
            {
              title: "Tierra Cocida",
              description: "Catálogo digital para productos artesanales. Visita: tierracocida.com",
              imageSrc: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=800",
            },
            {
              title: "Clínicas Peñarrubia",
              description: "Plataforma médica y de servicios de salud. Visita: clinicaspeñarrubia.com",
              imageSrc: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800",
            },
            {
              title: "FCS Explotaciones",
              description: "Presencia digital para servicios empresariales. Visita: fcsexplotaciones.com",
              imageSrc: "https://images.pexels.com/photos/38199714/pexels-photo-38199714.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=38199714",
            },
            {
              title: "Club Cadete",
              description: "Portal web interactivo para club deportivo. Visita: clubcadete.com",
              imageSrc: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=800",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
