// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "product" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductSection(): React.JSX.Element {
  return (
    <div id="product" data-section="product">
        <SectionErrorBoundary name="product">
              <FeaturesImageBento
          tag="Nuestro Portafolio"
          title="Excelencia en Cada Sector"
          description="Explora nuestros casos de éxito en clínicas, inmobiliarias y constructoras."
          items={[
            {
              title: "SB Capital",
              description: "Sitio web corporativo para empresa de inversión. Visita: sbcapital.es",
              imageSrc: "http://img.b2bpic.net/free-photo/office-worker-analyzing-business-charts-laptop-using-paperwork-research-information-make-data-report-working-from-home-startup-analysis-with-web-graphs-browsing-internet_482257-50961.jpg",
            },
            {
              title: "Tierra Cocida",
              description: "Catálogo digital para productos artesanales. Visita: tierracocida.com",
              imageSrc: "http://img.b2bpic.net/free-photo/stylish-clothing-boutique-interior_23-2151961902.jpg",
            },
            {
              title: "Clínicas Peñarrubia",
              description: "Plataforma médica y de servicios de salud. Visita: clinicaspeñarrubia.com",
              imageSrc: "http://img.b2bpic.net/free-photo/office-worker-analyzing-online-statistics-copy-space-mockup_482257-123748.jpg",
            },
            {
              title: "FCS Explotaciones",
              description: "Presencia digital para servicios empresariales. Visita: fcsexplotaciones.com",
              imageSrc: "http://img.b2bpic.net/free-photo/representation-user-experience-interface-design_23-2150169839.jpg",
            },
            {
              title: "Club Cadete",
              description: "Portal web interactivo para club deportivo. Visita: clubcadete.com",
              imageSrc: "http://img.b2bpic.net/free-photo/view-nutritional-counter-app_23-2149880610.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
