// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialSection(): React.JSX.Element {
  return (
    <div id="social" data-section="social">
        <SectionErrorBoundary name="social">
              <SocialProofMarquee
          tag="Confían en Nosotros"
          title="Pequeñas Empresas que Crecen con Nosotros"
          description="Ayudamos a negocios locales y emprendedores a establecer una presencia online sólida y profesional."
          names={[
            "Clínicas Peñarrubia",
            "FCS Explotaciones",
            "GrowthCo",
            "Avilés Clínica Dental",
            "DigitalWave",
            "CloudScale",
            "Tierra Cocida",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
