// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialQuoteCards from '@/components/sections/testimonial/TestimonialQuoteCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialQuoteCards
          tag="Casos de Éxito"
          title="Impulsando Resultados Juntos"
          description="No te quedes solo con nuestras palabras, descubre lo que opinan nuestros clientes."
          testimonials={[
            {
              name: "Dr. Carlos M.",
              role: "Director, Clínica Dental Sonrisas",
              quote: "Desde que lanzamos la nueva web, hemos duplicado las reservas de citas online. El diseño transmite la confianza que nuestros pacientes necesitan.",
              imageSrc: "http://img.b2bpic.net/free-photo/positive-middle-aged-business-leader-window_1262-5388.jpg",
            },
            {
              name: "Laura G.",
              role: "Gerente, Construcciones G&M",
              quote: "Digital Rocket entendió perfectamente nuestro sector. Ahora nuestro portafolio de proyectos luce increíble y atrae a clientes corporativos de alto nivel.",
              imageSrc: "https://images.pexels.com/photos/28386383/pexels-photo-28386383.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=28386383",
            },
            {
              name: "Roberto V.",
              role: "CEO, Inmobiliaria Vista",
              quote: "La velocidad de carga y la integración con nuestro CRM inmobiliario ha sido clave. Una inversión que se pagó sola en el primer mes.",
              imageSrc: "https://images.pexels.com/photos/7647213/pexels-photo-7647213.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=7647213",
            },
            {
              name: "Dra. Elena S.",
              role: "Fundadora, Centro Médico Avanzado",
              quote: "Profesionalidad absoluta. La página web es ahora nuestra principal herramienta de captación de pacientes privados.",
              imageSrc: "https://images.pexels.com/photos/6749777/pexels-photo-6749777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=6749777",
            },
            {
              name: "Miguel A.",
              role: "Socio, Arquitectura y Diseño",
              quote: "El equipo de Digital Rocket superó nuestras expectativas. Un diseño moderno y elegante que refleja exactamente lo que hacemos.",
              imageSrc: "https://images.pexels.com/photos/18604201/pexels-photo-18604201.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=18604201",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
